# Home Assistant bootc Example Configuration (TOML format)
# Copy this file to config.toml and customize for your environment

# User configuration
[[customizations.user]]
name = "ansible"
password = "changeme"
key = "ssh-rsa AAAAB3Nz.........."
groups = ["wheel"]

# Filesystem configuration
[[customizations.filesystem]]
mountpoint = "/"
minsize = "10 GiB"

[[customizations.filesystem]]
mountpoint = "/var/data"
minsize = "20 GiB"