# Home Assistant bootc Example Configuration (TOML format)
# Copy this file to config.toml and customize for your environment

# User configuration
[[blueprint.customizations.user]]
name = "ansible"
password = "changeme"
key = "ssh-rsa AAAAB3Nz.........."
groups = ["wheel"]

# Filesystem configuration
[[blueprint.customizations.filesystem]]
mountpoint = "/"
minsize = "10 GiB"

[[blueprint.customizations.filesystem]]
mountpoint = "/var/data"
minsize = "20 GiB"