name: Security Scanning

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Containerfile'
      - 'scripts/**'
      - 'bindep.txt'

jobs:
  dependency-check:
    name: Check Dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run dependency check script
      run: |
        chmod +x scripts/deps-check.sh
        ./scripts/deps-check.sh --security-only || true

    - name: Check for outdated packages
      run: |
        echo "Checking for outdated packages in bindep.txt..."
        # This would need actual implementation
        cat bindep.txt

  container-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get -y install podman

    - name: Build container image
      run: |
        podman build -t security-scan:latest .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'security-scan:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run Grype scanner
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
        grype security-scan:latest -o table

  code-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './scripts'
        severity: warning

    - name: Run hadolint on Containerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Containerfile
        failure-threshold: warning

  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run GitLeaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for hardcoded secrets
      run: |
        # Check for potential secrets
        if grep -r -E "(password|secret|key|token)\s*=\s*[\"'][^\"']+[\"']" --include="*.sh" --include="*.toml" --include="*.yml" .; then
          echo "⚠️ Potential hardcoded secrets found!"
          exit 1
        fi

  compliance-check:
    name: Compliance Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check license files
      run: |
        if [[ ! -f "LICENSE" ]]; then
          echo "ERROR: LICENSE file is missing"
          exit 1
        fi

    - name: Check security documentation
      run: |
        if [[ ! -f "SECURITY.md" ]]; then
          echo "ERROR: SECURITY.md file is missing"
          exit 1
        fi

    - name: Validate security configurations
      run: |
        # Check for security-related configurations
        echo "Checking security configurations..."
        grep -q "fail2ban" Containerfile || echo "WARNING: fail2ban not found"
        grep -q "firewall" Containerfile || echo "WARNING: firewall configuration not found"

  report:
    name: Security Report
    runs-on: ubuntu-latest
    needs: [dependency-check, container-scan, code-analysis, secret-scan, compliance-check]
    if: always()
    steps:
    - name: Create security report
      run: |
        echo "# Security Scan Report" > security-report.md
        echo "Date: $(date)" >> security-report.md
        echo "" >> security-report.md
        echo "## Summary" >> security-report.md
        echo "All security checks completed." >> security-report.md

    - name: Upload security report
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: security-report.md
        retention-days: 30